{
 "title": "OVHcloud Public Cloud Cost",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "from(bucket: \"pcicost\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ovhcloud_publiccloud_usage\")\n  |> group(columns: [\"project_name\"])\n|> distinct(column: \"project_name\")\n|> keep(columns: [\"_value\"])\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Total cost of all projects ",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"pcicost\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ovhcloud_publiccloud_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalPrice\")\n  //|> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\n  //|> aggregateWindow(every: 2h, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> fill(value: 0.0)\n  |> group(columns: [\"project_name\"])\n  |> keep(columns: [\"project_name\", \"_time\", \"_value\"])\n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\n  |> yield(name: \"price\")\n \n \n // |> truncateTimeColumn(unit: 30s)\n // |> aggregateWindow(every: 3600s, fn: sum, createEmpty: true)\n // \n // |> pivot(rowKey: [\"_time\"], columnKey: [\"project_name\"], valueColumn: \"_value\")\n\n\n//from(bucket: \"pcicost\")\n//  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n//  |> filter(fn: (r) => r[\"_measurement\"] == \"ovhcloud_publiccloud_usage\")\n//  |> filter(fn: (r) => r[\"_field\"] == \"totalPrice\")\n//  |> truncateTimeColumn(unit: 1h)\n//  |> aggregateWindow(every: 1h, fn: last, createEmpty: true)\n//  |> pivot(rowKey: [\"_time\"], columnKey: [\"project_name\"], valueColumn: \"_value\")\n   //|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   // |> group(columns: [\"_time\"])\n  //|> group(columns:[\"_time\"], mode:\"except\")\n //|> group(columns: [\"_value\"])\n //|> sum()\n   //|> group(columns: [\"_time\"])\n     //|> drop(columns: [\"_start\", \"_field\", \"_stop\", \"category\", \"host\", \"project_id\", \"region\", \"subcategory\", \"type\", \"reference\"])\n  //|> sum(column: \"_value\")\n  //|> group()"
    }
   ]
  },
  {
   "title": "Share of project",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"pcicost\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ovhcloud_publiccloud_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalPrice\")\n  |> group(columns: [\"project_name\"])\n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\n  |> yield(name: \"price\")\n \n  //|> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  //|> aggregateWindow(every: 1m, fn: mean, createEmpty: true)\n  //|> fill(usePrevious: true)\n  //|> fill(value: 0.0)"
    }
   ]
  },
  {
   "title": "Type of Instances",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"pcicost\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ovhcloud_publiccloud_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalPrice\")\n  |> filter(fn: (r) => r[\"reference\"] != \"\")\n  |> group(columns:[\"reference\"], mode: \"by\")\n  |> keep(columns:[\"reference\", \"_value\", \"_time\"])\n  |> rename(columns: {_value: \"\"})\n"
    }
   ]
  },
  {
   "title": "Category",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"pcicost\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ovhcloud_publiccloud_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalPrice\")\n  |> keep(columns:[\"category\", \"_value\", \"_time\"])\n  |> group(columns:[\"category\"], mode: \"by\")\n  |> rename(columns: {_value: \"\"})\n"
    }
   ]
  },
  {
   "title": "Region",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"pcicost\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ovhcloud_publiccloud_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalPrice\")\n  |> filter(fn: (r) => exists r.region)\n  |> fill(usePrevious: true)\n  |> fill(value: 0.0)\n  |> group(columns: [\"region\"])\n  |> keep(columns: [\"region\", \"_time\", \"_value\"])\n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\n  |> yield(name: \"price\")\n "
    }
   ]
  },
  {
   "title": "S3 Bucket Usage in €",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"pcicost\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ovhcloud_publiccloud_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalPrice\")\n  |> filter(fn: (r) => r[\"bucketName\"] != \"\")\n  |> group(columns:[\"bucketName\"], mode: \"by\")\n  |> keep(columns:[\"bucketName\", \"_value\", \"_time\"])\n  |> rename(columns: {_value: \"\"})\n"
    }
   ]
  },
  {
   "title": "Data for project ${project}",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"pcicost\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ovhcloud_publiccloud_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalPrice\")\n  |> filter(fn: (r) => r[\"project_name\"] == \"${project}\")\n  |> group()\n  |> yield(name: \"_results\")"
    }
   ]
  }
 ]
}